[package]
name = "dev-2"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
base58 = "0.2.0"
base64 = "0.22.1"
serde = "1.0.219"
serde_json = "1.0.140"
shuttle-axum = "0.55.0"
shuttle-runtime = "0.55.0"
solana-sdk = "2.3.1"
spl-token = "8.0.0"
tokio = "1.28.2"